vich_uploader:
    db_driver: orm
    # php 8
    metadata:
        type: attribute

    mappings:
        editeur:
            uri_prefix: /images/editeur
            upload_destination: '%kernel.project_dir%/public/images/editeur'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        livre:
            uri_prefix: /images/livre
            upload_destination: '%kernel.project_dir%/public/images/livre'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        auteur:
            uri_prefix: /images/auteur
            upload_destination: '%kernel.project_dir%/public/images/auteur'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        carousel:
            uri_prefix: /images/carousel
            upload_destination: '%kernel.project_dir%/public/images/carousel'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer